### ISSUE TITLE
unable to run the repo

### ISSUE THREAD

**Issue by prashantgpt91** [opensourceware/tagger#4]
I am getting this error while running the repo on word2vec word embeddings.

I know the error is due to non existent file. Can someone help me as where can i find that file?

Command used `python run.py --model_path models/neuralParsCit/ --pre_emb word2vec_twitter_model.bin --run shell` where `word2vec_twitter_model.bin` is the model is used.

```
Compiling...
Traceback (most recent call last):
  File "run.py", line 43, in <module>
    freq = json.load(open('/home/wenqiang/tagger-master/mydockerbuild2/mydockerbuild/freq', 'r'))
IOError: [Errno 2] No such file or directory: '/home/wenqiang/tagger-master/mydockerbuild2/mydockerbuild/freq'
```

**Comment by cmkumar87** [comment]
Hey @x0v 
You are looking for the binarized word vector file.
Could you please email animeshprasad3[AT]gmail[DOT]com (@animeshprasad) , cmkumar087 at gmail dot com for the dependent word vector files? 
Thanks!

**Comment by prashantgpt91** [comment]
@cmkumar87 I didn't get you?
Should I mail @animeshprasad to get this file `'/home/wenqiang/tagger-master/mydockerbuild2/mydockerbuild/freq` which is mentioned in line no. 42 of this [file](https://github.com/opensourceware/Neural-ParsCit/blob/master/run.py)

**Comment by prashantgpt91** [comment]
@cmkumar87 also please check my first comment which is now updated as I had resolved first error message but stuck in another.

**Comment by cmkumar87** [comment]
@x0v yes, we are aware of these dependencies and are in the process of integrating to our main pipeline.. so please email us so that we can help you to get this working

**Comment by prashantgpt91** [comment]
@cmkumar87 thankyou very much, I'll mail ASAP

**Comment by animeshprasad** [comment]
The file can now be accessed at WING homepage.
