### ISSUE TITLE
Gensim Deprecation warning

### ISSUE THREAD

**Issue by acepor** [opensourceware/tagger#5]
Hi there,

When I try to use run.py to experiment, we got such an error:

>   File "run.py", line 37, in <module>
    pretrained = gensim.models.word2vec.Word2Vec.load_word2vec_format(model.parameters['pre_emb'], binary=True)
  File "/neural_parscit/ENV/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1420, in load_word2vec_format
    raise DeprecationWarning("Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.")
DeprecationWarning: Deprecated. Use gensim.models.KeyedVectors.load_word2vec_format instead.

Then, I tried to replace this line with 

`pretrained = gensim.models.KeyedVectors.load_word2vec_format(model.parameters['pre_emb'], binary=True)`

I got this error:

>     with utils.smart_open(fname) as fin:
  File "/neural_parscit/ENV/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 135, in smart_open
    parsed_uri = ParseUri(uri)
  File "/neural_parscit/ENV/lib/python2.7/site-packages/smart_open/smart_open_lib.py", line 305, in __init__
    raise RuntimeError("invalid file URI: %s" % uri)
RuntimeError: invalid file URI:

Can you take a look at this problem?

Also, where can we find the freq file? Many thanks!

**Comment by animeshprasad** [comment]
You need to give path (vectors.bin) to word embedding and the freq file. Both of which can be downloaded from WING homepage now!
